# Generated by Django 3.2.25 on 2025-09-20 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recice',
            new_name='Recipe',
        ),
    ]
